name: Update Scholar Data

on:
  schedule:
    - cron: "1 3 * * 0"
  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Requirements
        run: pip install pandas scholarly boto3 plotly kaleido

      - name: Execute Python script
        run: |
          python .github/scripts/update.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          SCHOLAR_PROFILE_ID: ${{secrets.SCHOLAR_PROFILE_ID }}
